services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgre
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestion_produits
